### ISSUE TITLE
option to disable version and color code

### ISSUE THREAD

**Issue by gotbletu** [deadc0de6/catcli#12]
is there a way to disable this message, every time i run the command is wasting screen space
```
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.6.2

```

also is there a way to disable color code too?
for the most part i like the colors by default but sometime it is distracting,
i guess it depends on the person terminal color scheme but an option to toggle it off would be nice

**Comment by deadc0de6** [comment]
Hello, no currently there are no option for the two things you want. However I will implement them for you.
I'll add two cli switches: a `--no-banner` to disable the banner and a `--no-color` to disable the colors. Would that work for you?

**Comment by gotbletu** [comment]
yes thats perfect

**Comment by deadc0de6** [comment]
New version 0.7.0 releases with `-B --no-banner` to disable the banner and `-C --no-color` to disable the color.

**Comment by gotbletu** [comment]
Thanks, ill be sure to spread the word to everyone to use this now =)
