### ISSUE TITLE
edit parameter ends with error

### ISSUE THREAD

**Issue by laszlojanosek** [deadc0de6/catcli#14]
First of all, I really appreciate all work on this tool, as it helps me to catalog a large collection of archive data. Found an issue when I gave the wrong meta-information upon indexing, but I failed to correct it. I want to change meta information in a catalog using the following command:

        #catcli edit --catalog=Movies_Series.catalog 014

The command opens vim editor where I can modify and save (/w) the metadata. The editor is editing a file in a file /tmp/catcli6pfb08bh.tmp which reflects the change. When I quit the editor the following error message shown:

           +-+-+-+-+-+-+
           |c|a|t|c|l|i|
           +-+-+-+-+-+-+ v0.7.0
          
          Traceback (most recent call last):
            File "/home/lacmac/.local/bin/catcli", line 8, in <module>
              sys.exit(main())
            File "/home/lacmac/.local/lib/python3.8/site-packages/catcli/__init__.py", line 13, in main
              if catcli.catcli.main():
            File "/home/lacmac/.local/lib/python3.8/site-packages/catcli/catcli.py", line 277, in main
              cmd_edit(args, noder, catalog, top)
            File "/home/lacmac/.local/lib/python3.8/site-packages/catcli/catcli.py", line 213, in cmd_edit
              node.attr = noder.clean_storage_attr(new)node.attr = noder.clean_storage_attr(new)
          AttributeError: 'Noder' object has no attribute 'clean_storage_attr'

catcli ls shows the metadata not changed.

I understand I could remove the entry and add the index to the source again with correct metainformation, but I thought may be possible to correct the meta info with the edit parameter.

**Comment by deadc0de6** [comment]
Thanks a lot, happy `catcli` is useful to you.
It was indeed a bug and it should be fixed in version 0.7.2.

**Comment by laszlojanosek** [comment]
Perfect, work like a charm!
