### ISSUE TITLE
Feature request - additional data fields for csv format output

### ISSUE THREAD

**Issue by laszlojanosek** [deadc0de6/catcli#18]
The CSV output is a handy feature; many thanks. However, the native format still provides some data fields that are not available from CSV formatted output:

- meta
- nbfiles (nbchildren = len(node.children))
- remaining storage space (hf = utils.human(node.free))
- total available storage space (ht = utils.human(node.total))

Would you consider matching the printed data fields between native and CSV formats? 

**My current output in native:**

```
storage: 079 (Audio)
nbfiles:10 | totsize:881.3G | free:5.3% | du:49.3G/931.5G | date:2021-08-21 18:38:43
```

The same in csv:
`
"079","storage","","881.3G","2021-08-21 18:38:43","",""
`

Ideal output for me in CSV format would also include more fields from the native format, e.g:
`
"079","storage","","881.3G","2021-08-21 18:38:43","","","Audio","49.3G","931.5G"
`

Thank you for considering.

**Comment by deadc0de6** [comment]
Sure, I'll look into it and ping you when I have something concrete

**Comment by deadc0de6** [comment]
I added the requested fields in the [csv-extended branch](https://github.com/deadc0de6/catcli/tree/csv-extended). This simply produces following lines:
```
name,type,path,size,indexed_at,maccess,md5,nbfiles,free_space,total_space,meta
```

Note

* `free_space`, `total_space` and `meta` are always empty for nodes which are not storage nodes
* `nbfiles` are always empty for nodes which are not storage or directory nodes

Can you give it a try and let me know if that matches your expectation?

**Comment by deadc0de6** [comment]
Another idea would be to fill in the storage information on all nodes associated with it. This would produce something like
```
name,type,path,size,indexed_at,maccess,md5,nbfiles,storage_name,free_space,total_space,meta
```

which would end up with the fields `storage_name,free_space,total_space,meta` being always filled with the storage node information to which a node belong. Let me know what you think.

**Comment by laszlojanosek** [comment]
> I added the requested fields in the [csv-extended branch](https://github.com/deadc0de6/catcli/tree/csv-extended). This simply produces following lines:
> 
> ```
> name,type,path,size,indexed_at,maccess,md5,nbfiles,free_space,total_space,meta
> ```
> 
> Note
> 
> * `free_space`, `total_space` and `meta` are always empty for nodes which are not storage nodes
> * `nbfiles` are always empty for nodes which are not storage or directory nodes
> 
> Can you give it a try and let me know if that matches your expectation?

It is working perfectly fine for me, many thanks!

**Comment by laszlojanosek** [comment]
> Another idea would be to fill in the storage information on all nodes associated with it. This would produce something like
> 
> ```
> name,type,path,size,indexed_at,maccess,md5,nbfiles,storage_name,free_space,total_space,meta
> ```
> 
> which would end up with the fields `storage_name,free_space,total_space,meta` being always filled with the storage node information to which a node belong. Let me know what you think.

I think the "storage" related information is sufficient to provide at the storage level. Printing it with each node can be confusing as the data is not related to the node, but it's top level container. 
On the node level, the extra information is the node's size, which could be relevant. However, collecting such additional data impacts the processing time and increases the catalogue size.

Your currently presented modification in the CSV-extended branch perfectly fulfils my idea and will greatly help catalogue my media collection.

**Comment by deadc0de6** [comment]
Ok cool, I'll merge that and create a new version then.

**Comment by laszlojanosek** [comment]
many thanks, enjoy the coffee! ;-)

**Comment by deadc0de6** [comment]
New version 0.8.1 is available [on PyPi](https://pypi.org/project/catcli/)

Thanks!
