### ISSUE TITLE
Find is slow

### ISSUE THREAD

**Issue by fullofcaffeine** [deadc0de6/catcli#2]
The `find` is a bit slow for me. It takes 66.30 seconds for it to find an entry in an 1.9GB catalog:

```
catcli find python  66.30s user 3.09s system 99% cpu 1:09.56 total
```

System: 

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  OS: High Sierra
```

Is it normal for it to take that much time?

**Comment by deadc0de6** [comment]
More than a minute is slow, I agree!

When you say a 1.9GB catalog, you mean that the catcli catalog itself is 1.9GB or the indexed filesystem/directory?

In the background I directly call [anytree.findall](https://anytree.readthedocs.io/en/latest/api/anytree.search.html) without much fuss

https://github.com/deadc0de6/catcli/blob/4cb01125aca98f3c044caf6d7818ef9d8e2f71a3/catcli/noder.py#L201

It is walking the tree node by node. I see a few solutions to improve searching:
* add the ability to filter on specific part of the indexed tree.
* create a search index for faster search.
* indexing the filesystem/directory in different sub-tree of the catalog and point the search on specific branches only.

It is difficult to say without much information on what you are indexing. I'm guessing what you index is a filesystem/directory with very deep hierarchy and many files?

**Comment by deadc0de6** [comment]
@fullofcaffeine got it sorted ?
