### ISSUE TITLE
Double quotes in file names or paths not escaped in CSV output

### ISSUE THREAD

**Issue by mwalker** [deadc0de6/catcli#22]
Thanks for a great tool, it's been really useful.

I have some files that have double quotes in their names, and sqlite errors on importing the CSV file because it doesn't like the format. It seems the generally the best way is to escape double quotes with a second double quote preceding it (there's more detail here as CSV is not well specified – <https://docs.python.org/3/library/csv.html>).

I've got this working for myself and will attach a pull request to here shortly.

**Comment by mwalker** [comment]
I've created https://github.com/deadc0de6/catcli/pull/23 with a simple fix

**Comment by deadc0de6** [comment]
Awesome, thanks a lot for you help!

**Comment by deadc0de6** [comment]
The version v0.8.6 with the fix is available on pypi: https://pypi.org/project/catcli/
