### ISSUE TITLE
[feature request] fzf support

### ISSUE THREAD

**Issue by cocoonkid** [deadc0de6/catcli#26]
First let me thank you for this amazing tool!

Finally I can search through all my NAS files conveniently and offline too! and damn is that indexing fast!!!!

So now I found it would be really neat if I could use fzf instead of find to fuzzy search through the catalog. 

Piping works but in this case I'd be able to remove metadata e.g only query the filenames.

And to be able to persist the "fzf" settings for each catalog.

The config file could also be use to be able to schedule catcli catalog updates like in my case I'd like to update the catalog for each of 11 folders on my NAS once every 24 hours at 4 am.

This tool is a gamechanger especially with the power of fzf.

Thank you for your consideration.

**Comment by deadc0de6** [comment]
You are very welcome, happy it helps :+1: 

I could add a cli switch for `find` to use `fzf` like `catcli find --fzf`. Another way would be to add an environment variable like `CATCLI_FIND=fzf` which would tell catcli to use fzf when `CATCLI_FIND` is defined. , Would that work for you? Of course if `fzf` is used then catcli would only list the filenames.

I'm not sure what you mean by
> And to be able to persist the "fzf" settings for each catalog.

Can you elaborate?

Regarding scheduled updates, what about using crontab for example?
```
## update folder1 at 4am
0 1 * * * catcli update --catalog <path-to-catalog> folder1 /folder1
## update folder2 at 4:05 am
5 1 * * * catcli update --catalog <path-to-catalog> folder2 /folder2
## update folder3 at 4:10 am
10 1 * * * catcli update --catalog <path-to-catalog> folder3 /folder3
```

**Comment by cocoonkid** [comment]
Both would be perfectly fine. As it suits you best.

With persisting the settings I meant which kind of data fzf is supposed to search through depending on the target catalog.

For example in my mp3 path I'd like to fzf only the filenames, but in my PDF folder I'd like to search through the content of  PDF's & epubs themselves as well but then I realised I was thinking ahead since catcli doesn't index PDF nor epubs :-)

So fzf -> search filenames only is totally fine!

Hope that made sense.


Yes cronjobs totally work and thank you for the examples.

I initially meant something internal to catcli would make sense but I see this is not a must-have core functionality.

**Comment by deadc0de6** [comment]
@cocoonkid I made an attempt at `fzf` in the [fzf branch](https://github.com/deadc0de6/catcli/tree/fzf). It adds two additional formats to the `find` command:

* `--format=fzf-native`: allows to choose using fzf from the list of all nodes under the selected path (if any) and displays the result in native format
* `--format=fzf-csv`: allows to choose using fzf from the list of all nodes under the selected path (if any) and displays the result in csv

You should be able to test it simply with
```bash
$ git clone https://github.com/deadc0de6/catcli.git
$ cd catcli
$ git checkout fzf
$ pip3 install -r requirements.txt --user
$ python3 -m catcli.catcli --help
```

Let me know if this match your expectations

**Comment by cocoonkid** [comment]
@deadc0de6 My apology for taking so long to reply.

I will try this out very soon but it looks already precisely like what I have been looking for.


Thanks a big bunch!

**Comment by deadc0de6** [comment]
@cocoonkid this was integrated in the main branch and will be part of the next release.
