### ISSUE TITLE
sister project: decoyfs

### ISSUE THREAD

**Issue by hydrargyrum** [deadc0de6/catcli#28]
A few weeks ago, I had a similar need to catcli but didn't know about catcli, so I built my own indexer and a fuse filesystem for browsing an offline catalog: [decoyfs](https://github.com/hydrargyrum/decoyfs). Today I came across catcli and realized things would have been different if I found it before :)

I added a converter tool in decoyfs so it can load catcli catalogs and show it as a vfs. decoyfs has a quite liberal license, so feel free to steal some code if you want a fuse filesystem for catcli!

**Comment by deadc0de6** [comment]
hey @hydrargyrum, thanks a lot for the convertor. I really like the fuse filesystem approach, that's pretty neat. Yeah if that's ok with you I might integrate a fuse filesystem in catcli.

**Comment by hydrargyrum** [comment]
Yes, you can go for it, that's what free software is for after all! I can help with some of the fuse stuff if you want (I made decoyfs really quick-and-dirty, there's room for improvement anyway).

**Comment by deadc0de6** [comment]
@hydrargyrum catcli now supports fuse filesystem through the use of the command line action `mount`, see the [related doc in the readme](https://github.com/deadc0de6/catcli#mount-catalog).

Thanks again for the heads-up!

**Comment by hydrargyrum** [comment]
You're welcome :)
happy if it helped
