### ISSUE TITLE
No way to update?

### ISSUE THREAD

**Issue by rolfen** [deadc0de6/catcli#3]
I want to use this for external disks. Say I modify a file on my disk, how can I update the catalog? `catcli` complains "storage named NNNNN already exist".

By the way both the `-r` (recursive) and `-f` (force) arguments are ignored by `catcli index` despite the documentation.

**Comment by deadc0de6** [comment]
Thanks for reporting this.

There is no `update` command yet. I could add one that removes the entry and re-index the content. Currently the way of doing this is to first remove the current storage and re-add it, not optimal, I agree. I'll work on that.

The recursive option (`-r --recursive`) is not available for `index` but only to `ls`. `index` is recursive per default. See `catcli index  [--catalog=<path>] [--meta=<meta>...] [-acfuV] <name> <path>`. Where in the doc did you find that `-r` is available to `index`?

The force (`-f --force`) is not ignored, it actually applies to the update of the catalog and not to the storage being added. I will update the doc to make it more clear. Let's say you have a catalog already and add a new storage, per default catcli will ask you if you want to update the catalog, with the `--force` switch you can avoid that. For example:
```bash
$ python3 -m catcli.catcli index downloads ~/Downloads
Indexed 250 file(s) in 0:00:00.017901
$ python3 -m catcli.catcli index downloads2 ~/Downloads
Indexed 250 file(s) in 0:00:00.013431                                                     
Overwrite "catcli.catalog" [y|N] ? N
Catalog not saved
$ python3 -m catcli.catcli index downloads2 ~/Downloads  -f
Indexed 250 file(s) in 0:00:00.011354
```

**Comment by deadc0de6** [comment]
I have updated catcli and you are not able to re-index an existing storage using the `index` command. New version is available on github and pypi.

**Comment by rolfen** [comment]
Thank you.
I expected `-r` and `-f` to work according to the help output printed by the `catcli` command. Sorry for the bad wording.

**Comment by deadc0de6** [comment]
Yeah, you're right, being able to have only parts of the storage recalculated would be nice. I keep this open and will work on it.

**Comment by deadc0de6** [comment]
I have implemented the *dynamic* re-indexing by checking file access time. It is available in the new version. Let me know if you're having any issue. Thanks!

**Comment by rolfen** [comment]
> I have implemented the _dynamic_ re-indexing by checking file access time. It is available in the new version. Let me know if you're having any issue. Thanks!

Awesome! I'll try it out.

**Comment by rolfen** [comment]
This is very nice, it works as expected. When I use `update` with `-c` it only calculates checksums for the files that have changed.
Tested on Windows 7.
Thank you for the good work.

**Comment by rolfen** [comment]
Actually there is one potential issue: if I delete a file, this is not detected by `update` and the file is still referenced in the catalog.

**Comment by deadc0de6** [comment]
I have made some changes that should take into account the removing of files, if you happen to test it, let me know. Thanks!

**Comment by deadc0de6** [comment]
New version is on pypi.
Thanks for your help :+1:

**Comment by rolfen** [comment]
Sorry I was a bit busy, I just tested it, I can confirm it detects deletion. Pretty cool, Thank you!
