### ISSUE TITLE
Problems with fuse

### ISSUE THREAD

**Issue by rflgrt** [deadc0de6/catcli#31]
Hi, 

I tried to install catcli on Ubuntu 20.04 with Python 3.9 using pip3.
After pip3 install catcli, python3 complained: 
`ModuleNotFoundError: No module named 'fuse'`

After pip3 install fuse (installed fuse-0.1.3),  trying to index a directory resulted in
`class CatcliFilesystem(fuse.LoggingMixIn, fuse.Operations):  # type: ignore`
`AttributeError: module 'fuse' has no attribute 'LoggingMixIn' `

Best wishes

**Comment by deadc0de6** [comment]
Hello,

Sorry I forgot to update the dependencies in the `setup.py` file. You can temporarly fix it by doing 
```bash
pip3 install --user fusepy
```

I will release a new version with the deps updated.
Thanks for your patience!

**Comment by deadc0de6** [comment]
[Version 0.9.2 is released](https://pypi.org/project/catcli/) and should have the issue fixed.

**Comment by rflgrt** [comment]
Thanks a lot for fixing so quickly! Installation with pip3 works now.
