### ISSUE TITLE
AUR package stopped working

### ISSUE THREAD

**Issue by deathtrip** [deadc0de6/catcli#32]
After using an old version, i wanted to try the new features. So i compiled an updated [git package](https://aur.archlinux.org/packages/catcli-git), and things stopped working. I get this error when trying to index data:
> File "/usr/bin/catcli", line 33, in <module>
    sys.exit(load_entry_point('catcli==0.9.2', 'console_scripts', 'catcli')())
  File "/usr/lib/python3.10/site-packages/catcli/__init__.py", line 12, in main
    import catcli.catcli
  File "/usr/lib/python3.10/site-packages/catcli/catcli.py", line 23, in <module>
    from catcli.walker import Walker
  File "/usr/lib/python3.10/site-packages/catcli/walker.py", line 12, in <module>
    from catcli.noder import Noder
  File "/usr/lib/python3.10/site-packages/catcli/noder.py", line 13, in <module>
    from pyfzf.pyfzf import FzfPrompt  # type: ignore
ModuleNotFoundError: No module named 'pyfzf'`

Looks like the dependencies need to be updated.
I'm filing this issue here as i saw that you also maintain the AUR package, but since it wasn't updated in quite some time, i wasn't sure i would get a response in the package comments.

**Comment by deadc0de6** [comment]
@deathtrip thanks for pointing it out. I fixed it and added the two missing dependencies

* [python-pyfzf on aur](https://aur.archlinux.org/packages/python-pyfzf) - [pyfzf on pypi](https://pypi.org/project/pyfzf/)
* [python-fusepy on aur](https://aur.archlinux.org/packages/python-fusepy) - [fusepy on pypi](https://pypi.org/project/fusepy/)

**Comment by deadc0de6** [comment]
I also released a new version (`v0.9.3`) which makes the dependencies on those two libraries optional (you just won't be able to use fzf for listing/finding and mount your catalog using fuse if not installed).
