### ISSUE TITLE
Example in the README: problem with 'echo' redirection command 

### ISSUE THREAD

**Issue by m040601** [deadc0de6/catcli#33]
I dont know which shell and OS you are using but on my system,

```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```
```
Linux gigabyty 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
```

This example listed on the README,

```
echo 'something in files in a' > /tmp/test/a/{1,2,3}
```

does not work,

```
-bash: /t-bash: /tmp/test/a/{1,2,3}: ambiguous redirect
```

I suppose you cant use echo and ">" and {} brace expansion altogether like that.

This works,

```
echo hello >file1 >file2 >file3
```

And this, only file1 gets created.

```
echo hello > file1 file2 file3
```

**Comment by deadc0de6** [comment]
hello, [zsh](https://www.zsh.org/) allows you to do that, you should give it a try ;-)
