### ISSUE TITLE
AttributeError: can't set attribute when trying to use catcli index.

### ISSUE THREAD

**Issue by DrChr** [deadc0de6/catcli#36]
I'm new to `catcli`, so I'm not sure if the error message below is due to me or a bug. If it's a user error, I'd like to suggest improving the readability of the error message...

Note: I haven't gotten 'catcli' to work at all so far. I'm getting the error the first time I tried to use `catcli`. The output below is from after having switched to an absolute path.

Note: I installed 'catcli' with pip3.

Any suggestions on how to troubleshoot this, or if I should first try some easier example or so?

```
~/playground/catcli/tc-01$ catcli index --meta="Some description" my-name-for-ds-01 /home/chr/playground/data-sets/ds-01
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.9.4

Traceback (most recent call last):
  File "/home/chr/.local/bin/catcli", line 8, in <module>
    sys.exit(main())
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/__init__.py", line 13, in main
    if catcli.catcli.main():
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/catcli.py", line 337, in main
    cmd_index(args, noder, catalog, top)
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/catcli.py", line 125, in cmd_index
    root = noder.new_storage_node(name, path, top, attr)
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/noder.py", line 252, in new_storage_node
    return NodeStorage(name,
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/nodes.py", line 179, in __init__
    self.size = size
AttributeError: can't set attribute
```

**Comment by deadc0de6** [comment]
Hello, it's indeed a bug, however I'm puzzled as to why it suddenly happened while the tests ran successfully 2 month ago.

If you're in python, this is the reason:
```python
class A:
    @property
    def size(self):
        return 1

class B(A):
    def __init__(self):
        super().__init__()

    def set_size(self, val):
        self.size = val

if __name__ == '__main__':
    b = B()
    b.set_size(4)
    print(b.size)   
```
For ref <https://github.com/c0fec0de/anytree/blob/main/anytree/node/nodemixin.py#L508>

**Comment by deadc0de6** [comment]
Verison 0.9.5 now available [in pypi](https://pypi.org/project/catcli/) is fixed. Thanks for reporting this!

**Comment by DrChr** [comment]
I can confirm it now works with v0.9.5 (it took a while for me to get back to this).
Thank you very much for fixing the bug so quickly.
