### ISSUE TITLE
catcli mount not working - fusermount: option allow_other only allowed if ...

### ISSUE THREAD

**Issue by DrChr** [deadc0de6/catcli#38]
The command to mount via catcli throws an error. Is it a bug or a me doing something wrong?
If fuse needs some special config options, perhaps the documention should mention this at https://github.com/deadc0de6/catcli#mount-catalog ?

Creating the catalog:
~/playground/catcli/tc-01$ catcli index --meta="Some description" my-name-for-ds-01 ../../data-sets/ds-01
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.9.5`

Indexed 14 file(s) in 0:00:00.000824                                                      

Trying to mount it with catcli:
~/playground/catcli/tc-01$ mkdir --parent mnt
~/playground/catcli/tc-01$ catcli mount mnt
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.9.5

fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
Traceback (most recent call last):
  File "/home/chr/.local/bin/catcli", line 8, in <module>
    sys.exit(main())
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/__init__.py", line 13, in main
    if catcli.catcli.main():
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/catcli.py", line 357, in main
    if not cmd_mount(args, top, noder):
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/catcli.py", line 90, in cmd_mount
    Fuser(mountpoint, top, noder,
  File "/home/chr/.local/lib/python3.8/site-packages/catcli/fuser.py", line 33, in __init__
    fuse.FUSE(filesystem,
  File "/home/chr/.local/lib/python3.8/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)

**Comment by deadc0de6** [comment]
Thanks for reporting this. Indeed the `allow_other` is probably not needed. I'll remove it and release a new version.

For the record `allow_other` allows different users that the one who mounted the directory to access the files:
```
allow_other
              This option overrides the security measure restricting  file  access  to  the  user
              mounting the filesystem.  So all users (including root) can access the files.  This
              option is by default only allowed to root, but this restriction can be removed with
              a configuration option described in the previous section.
```
from <https://manpages.ubuntu.com/manpages/xenial/man8/mount.fuse.8.html>

**Comment by deadc0de6** [comment]
It should be fixed in the master branch, I'll release a new version ASAP

**Comment by deadc0de6** [comment]
Fixed in the [new version 0.9.6 available on pypi](https://pypi.org/project/catcli/)

**Comment by DrChr** [comment]
Confirmed.
A question though (I can create a separate issue if youd' like).

Should the mounted directories really be writable by 'other'?

```
$ find mnt/my-name-for-ds-01/data -type d -ls
        7      0 drwxrwxrwx  mnt/my-name-for-ds-01/data
       10      0 drwxrwxrwx  mnt/my-name-for-ds-01/data/photos_Nikon_D800
```

Perhaps the topic of what permissions the mounted tree should have deserves it's own topic... does it ever make sense to be able to modify something in the mounted view of the catalog?

**Comment by deadc0de6** [comment]
@DrChr I opened a new issue for discussing this [here](https://github.com/deadc0de6/catcli/issues/41)
