### ISSUE TITLE
find should show the location

### ISSUE THREAD

**Issue by weberjn** [deadc0de6/catcli#44]
find should show the path of the found file
```
catcli -B find fstab
/etc/fstab [size:902, storage:etc]
```

**Comment by deadc0de6** [comment]
@weberjn this feature has been added in the branch [features-42](https://github.com/deadc0de6/catcli/tree/features-42). Could you give it a try? 
You can get it like this:
```bash
git clone https://github.com/deadc0de6/catcli.git
cd catcli
git checkout features-42
python3 -m catcli.catcli -B find --catalog=<catalog-path> fstab
```
