### ISSUE TITLE
catcli should have a du command

### ISSUE THREAD

**Issue by weberjn** [deadc0de6/catcli#46]
similar to [du(1)](https://www.freebsd.org/cgi/man.cgi?du)
with -s option
```
catcli -B du temptst/etc
3.2M    /etc
```

**Comment by deadc0de6** [comment]
@weberjn this feature has been added in the branch [features-42](https://github.com/deadc0de6/catcli/tree/features-42). Could you give it a try? 
You can get it like this:
```bash
git clone https://github.com/deadc0de6/catcli.git
cd catcli
git checkout features-42
python3 -m catcli.catcli -B du --catalog=<catalog-path> <something-here>
```
