### ISSUE TITLE
Show date of last update / creation

### ISSUE THREAD

**Issue by de-ramon** [deadc0de6/catcli#5]
Hi,

IMHO showing the date of the index update /creation would be useful, e.g.:

catcli ls some-name
   storage: some-name (free:800G, total:1T, date: 2018-09-26 07:16:44)
   - catcli-0.3.1 [nbfiles:11, totsize:80.5K]
   - v0.3.1.tar.gz [size:24.2K]
   - v0.3.1.zip [size:31.2K]

thx,

ramon

**Comment by deadc0de6** [comment]
Sure, I've added it with the latest commit.

**Comment by deadc0de6** [comment]
New version was released
Thanks for the suggestion!

**Comment by de-ramon** [comment]
;-) :+1: :1st_place_medal:
