### ISSUE TITLE
Recursion!

### ISSUE THREAD

**Issue by VegaDeftwing** [deadc0de6/catcli#9]
![DeepinScreenshot_select-area_20200319024011](https://user-images.githubusercontent.com/11283620/77043195-03012a00-698b-11ea-8af3-e510061947b5.png)

Issue is pretty self explanatory

**Comment by deadc0de6** [comment]
no it's not, please elaborate

**Comment by VegaDeftwing** [comment]
When a symlink points to another symlink in a recursive manner catcli can
get trapped resulting in path a/b/b/b/b/b... where /b is the symlink
location

**Comment by deadc0de6** [comment]
It should be fixed in [recursion branch](https://github.com/deadc0de6/catcli/tree/recursion), can you give it a try?
